language: cpp

matrix:
 include:
  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - sourceline: "ppa:beineri/opt-qt487-trusty"
        packages:
          - opt-qt4-qmake
          - opt-qt4-dev-tools
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=48
  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
        packages:
          - qt510base
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=510
  - os: osx
    compiler: clang
    env:
     - QT_BASE=57

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      brew update;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      brew install qt5;
      brew link --force qt5;
      wget https://github.com/leozide/leocad/releases/download/v0.83.2/Library-Linux-9306.zip -O library.bin;
    fi

script:
  - if [[ "$QT_BASE" = "48" && "$TRAVIS_OS_NAME" = "linux" ]]; then source /opt/qt-4.8/bin/qt-4.8-env.sh; fi
  - if [[ "$QT_BASE" = "510" && "$TRAVIS_OS_NAME" = "linux" ]]; then source /opt/qt510/bin/qt510-env.sh; fi
  - qmake PREFIX=/usr -v
  - qmake PREFIX=/usr -r
  - make -j4
  - if [ "$TRAVIS_OS_NAME" != "linux" ] ; then exit 0 ; fi
  - sudo apt-get -y install checkinstall
  - rm ./*.spec # Otherwise the next line fails
  - sudo checkinstall --pkgname=app --pkgversion="1" --pkgrelease="1" --backup=no --fstrans=no --default --deldoc 
  - mkdir appdir ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; find .
  - cp ../qt/leocad.desktop .
  - sed -i -e 's|\.svg||g' leocad.desktop # Workaround
  - cp ../resources/leocad.png .
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage 
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD)
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/leocad -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/leocad -appimage 
  - curl --upload-file ./LeoCAD-*.AppImage https://transfer.sh/LeoCAD-git.$VERSION.qt$QT_BASE-x86_64.AppImage 
  
